version: "3.8"
services:
  app:
    build: 
      context: .
    volumes:
      - .:/core
    ports:
      - 3000:3000
    image: app:TEXT-ANALYZER
    container_name: TEXT-ANALYZER_container
    command: npm start